PACKAGE_NAME="bbrx"
PACKAGE_VERSION="0.1.1"
BUILT_MODULE_NAME[0]="tcp_bbrx"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
